import streamlit as st 
from streamlit_option_menu import option_menu
import pymysql as sql
import pandas as pd
import numpy as np
from PIL import Image
import random



# CONNECT TO SQL

conn = sql.connect(host='localhost', user='root',port = 3306, password='admin@123', db='comp_mgmt_sys')
cur = conn.cursor()

# ============================================       /     STREAMLIT DASHBOARD      /       ================================================= #

# Configuring Streamlit GUI

st.set_page_config(layout="wide")

selected = option_menu(None,
                       options = ["Home","Register","View"],
                       icons = ["house","toggles","at"],
                       default_index=0,
                       orientation="horizontal",
                       styles={"container": {"width": "100%"},
                               "icon": {"color": "white", "font-size": "24px"},
                               "nav-link": {"font-size": "24px", "text-align": "center", "margin": "-2px"},
                               "nav-link-selected": {"background-color": "#1e4d2b"}})


def autogenerated_number():
    lett = state['letter']
    num = state['value']
    reg_no = lett + str(num)
    return reg_no

letter_list = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','U','V','W','X','Y','Z']
state = {'value': random.randrange(1000, 5000, 1),'letter':random.choice(letter_list)}
if selected == "Home":
    st.title("COMPLAINT MANAGEMENT SYSTEM")
    st.image(Image.open("C:/Users/mahes/Downloads/cms.png"))
    
if selected == "Register":
    st.header("TO REGISTER COMPLAINT FILL BELOW FORM")   
    comp_num =  autogenerated_number()
    st.write("COMPLAINT NUMBER : ", comp_num)
    customer_name = st.text_input("CUSTOMER_NAME:")
    complaint = st.text_input("COMPLAINT:")
    description = st.text_input("DESCRIPTION:")
    mobile_number = st.text_input("CONTACT NUMBER:")
    email = st.text_input("EMAIL ID:")
    values = (comp_num,customer_name,complaint,description,mobile_number,email)
    sql_query = "INSERT INTO cms(complaint_id,customer_name,complaint,complaint_description,contact_number,email) VALUES (%s, %s, %s, %s, %s, %s)"
    if st.button("SUBMIT"):
    # Execute the query
        cur.execute(sql_query, tuple(values))
        
        # Commit the changes
        conn.commit()
        st.success("Complaint Successfully Registered")

if selected == "View":
    st.header("CHECK OR VIEW YOUR COMPLAINT")
    cust_id = st.text_input("ENTER COMPLAINT ID:")
    id1 = str(cust_id)
    sql_query1 = f'''SELECT * FROM cms WHERE complaint_id = {id1}'''
    if st.button("RETRIEVE"):
        cur.execute(sql_query1)
        df_info = pd.DataFrame(cur.fetchall(), columns = ["CUSTOMER_ID","CUSTOMER_NAME","COMPLAINT","COMPLAINT_DESCRIPTION","CONTACT_NO","EMAIL"])
        st.success("INFORMATION RETRIEVED")
        st.dataframe(df_info)
        

